**INSTALL NUMPY**

In [ ]:
!pip install numpy

**IMPORT NUMPY**

In [ ]:
import numpy as np

**AGGREGATE FUNCTIONS**

*FOR SINGLE DIMENSIONAL ARRAY*

In [ ]:
#sum() calculates the total of both floating-point numbers and integers.
num = np.array([3,5,7])
print(num.sum())

15


In [ ]:
# min() function is used to find the lowest value in a list.
num = np.array([4,6,8])
print(num.min())

4


In [ ]:
#max() function is used to find the largest value in a list of values. 
num = np.array([3,2,1])
print(num.max())

3


In [ ]:
# mean() function is used to calculate mean/average of a given list of numbers
num = np.array([7,8,9])
print(num.mean())

8.0


In [ ]:
#prod() used to calculate the product of all the elements present in the given iterable.
num = np.array([5,7,3])
print(num.prod())

105


In [ ]:
# The method returns the __dict__ attribute for a module, class, instance, or any other object if the same has a __dict__ attribute.
num = np.array([6,7,8])
print(num.var())

0.6666666666666666


In [ ]:
# median() is used to calculate the median of any data set without first sorting the list.
num = np.array([5,7,9])
print(np.median(num))

7.0


In [ ]:
#cumsum() is used to find the cumulative sum value over any axis.
num = np.array([5,7,9])
num
np.cumsum(num)

array([ 5, 12, 21])

In [ ]:
#cumprod() function is used when we want to compute the cumulative product of array elements over a given axis.
num = np.array([5,7,9])
num
np.cumprod(num)

array([  5,  35, 315])

In [ ]:
#percentile()function used to compute the nth percentile of the given data (array elements) along the specified axis.
num = np.array([5,7,9])
num
np.percentile(num,1)

5.04

In [ ]:
#Correlation coefficients are used to measure the strength of the relationship between two variables.
num = np.array([5,7,9,11])
num
np.corrcoef(num)

1.0

In [ ]:
# minimum array
a=[4,5,6]
b=[7,8,9]
print(np.minimum(a,b))

[4 5 6]


In [ ]:
# maximum array
a=[4,5,6]
b=[7,8,9]
print(np.maximum(a,b))

[7 8 9]


*FOR TWO DIMENSIONAL ARRAY*

In [ ]:
num = np.array([[3,5,7],[3,5,7]])
print(num.sum())

30


In [ ]:
num = np.array([[4,6,8],[7,9,6]])
print(num.min())

4


In [ ]:
num = np.array([[3,2,1],[9,5,3]])
print(num.max())

9


In [ ]:
num = np.array([[7,8,9],[3,8,9]])
print(num.mean())

7.333333333333333


In [ ]:
num = np.array([[5,7,3],[8,3,2]])
print(num.prod())

5040


In [ ]:
num = np.array([[6,7,8],[3,4,5]])
print(num.var())

2.9166666666666665


In [ ]:
num = np.array([[3,5,7],[4,5,6]])
print(np.average(num))

5.0


In [ ]:
a=[[4,5,6],[9,8,7]]
b=[[7,8,9],[6,5,4]]
print(np.minimum(a,b))

[[4 5 6]
 [6 5 4]]


In [ ]:
x=[[4,5,6],[3,4,5]]
y=[[7,8,9],[4,5,6]]
print(np.maximum(x,y))

[[7 8 9]
 [4 5 6]]


In [ ]:
num = np.array([[5,7,9],[8,3,1]])
print(np.median(num))

6.0


In [ ]:
num = np.array([[5,7,9],[0,9,8]])
num
np.cumsum(num)

array([ 5, 12, 21, 21, 30, 38])

In [ ]:
num = np.array([[5,7,9],[8,5,4]])
num
np.cumprod(num)

array([    5,    35,   315,  2520, 12600, 50400])

In [ ]:
num = np.array([[5,7,9],[5,4,3]])
num
np.percentile(num,1)

3.05

In [ ]:
num = np.array([[5,7,9,11],[2,3,4,5]])
num
np.corrcoef(num)

array([[1., 1.],
       [1., 1.]])

*FOR MULTI DIMENSIONAL ARRAY*

In [ ]:
num = np.array([[5,7,9,11],[2,3,4,5],[3,4,5,7],[2,5,6,8]])
print(num.sum())

86


In [ ]:
num = np.array([[5,7,9,11],[2,3,4,5],[3,4,5,7],[2,5,6,8]])
print(num.min())

2


In [ ]:
num = np.array([[5,7,9,11],[2,3,4,5],[3,4,5,7],[2,5,6,8]])
print(num.max())

11


In [ ]:
num = np.array([[5,7,9,11],[2,3,4,5],[3,4,5,7],[2,5,6,8]])
print(num.mean())

5.375


In [ ]:
num = np.array([[5,7,9,11],[2,3,4,5],[3,4,5,7],[2,5,6,8]])
print(num.prod())

83825280000


In [ ]:
num = np.array([[5,7,9,11],[2,3,4,5],[3,4,5,7],[2,5,6,8]])
print(num.var())

5.984375


In [ ]:
num = np.array([[5,7,9,11],[2,3,4,5],[3,4,5,7],[2,5,6,8]])
print(np.average(num))

5.375


In [ ]:
num = np.array([[5,7,9,11],[2,3,4,5],[3,4,5,7],[2,5,6,8]])
print(np.median(num))

5.0


In [ ]:
num = np.array([[5,7,9,11],[2,3,4,5],[3,4,5,7],[2,5,6,8]])
num
np.cumsum(num)

array([ 5, 12, 21, 32, 34, 37, 41, 46, 49, 53, 58, 65, 67, 72, 78, 86])

In [ ]:
num = np.array([[5,7,9,11],[2,3,4,5],[3,4,5,7],[2,5,6,8]])
num
np.cumprod(num)

array([          5,          35,         315,        3465,        6930,
             20790,       83160,      415800,     1247400,     4989600,
          24948000,   174636000,   349272000,  1746360000, 10478160000,
       83825280000])

In [ ]:
num = np.array([[5,7,9,11],[2,3,4,5],[3,4,5,7],[2,5,6,8]])
num
np.percentile(num,1)

2.0

In [ ]:
num = np.array([[5,7,9,11],[2,3,4,5],[3,4,5,7],[2,5,6,8]])
num
np.corrcoef(num)

array([[1.        , 1.        , 0.98270763, 0.98115578],
       [1.        , 1.        , 0.98270763, 0.98115578],
       [0.98270763, 0.98270763, 1.        , 0.95638207],
       [0.98115578, 0.98115578, 0.95638207, 1.        ]])

In [ ]:
a=[[4,5,6],[3,4,5],[4,5,6],[2,1,3]]
b=[[7,8,9],[4,5,6],[4,5,6],[2,3,4]]
print(np.minimum(a,b))

[[4 5 6]
 [3 4 5]
 [4 5 6]
 [2 1 3]]


In [ ]:
x=[[4,5,6],[3,4,5],[4,5,6],[2,1,3]]
y=[[7,8,9],[4,5,6],[4,5,6],[2,3,4]]
print(np.maximum(x,y))

[[7 8 9]
 [4 5 6]
 [4 5 6]
 [2 3 4]]


 **RANDAMIZE FUNCTION** 

In [ ]:
x=np.random.rand(5)
x

array([0.3319397 , 0.98739364, 0.48180773, 0.60891324, 0.0400023 ])

In [ ]:
x=np.random.randn(8)
x

array([ 0.83408616, -1.5236864 ,  0.75738753, -0.90470162,  0.35487881,
        1.38977522,  0.85033624,  1.41530724])

In [ ]:
#Returns a random number between the given range
x=np.random.randint(1,9)
x

8

In [ ]:
x=np.eye(3)
x

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
x=np.ones(6)
x

array([1., 1., 1., 1., 1., 1.])