**SORTING**

**SYNTAX**

In [ ]:
numpy.sort(a, axis, kind, order) 
#a denotes input

**IMPORT NUMPY**

In [ ]:
import numpy as np


**FOR ONE DIMENSION ARRAY**

In [ ]:
arr = np.array([True, False, True])
print(np.sort(arr))

[False  True  True]


**FOR TWO DIMENSION ARRAY**

In [ ]:
arr = np.array([[3, 2, 4], [5, 0, 1]])
print(np.sort(arr))

[[2 3 4]
 [0 1 5]]


**CREATE A MATRIX**

In [ ]:
np.random.seed(77)
array2d=np.random.choice(a=np.arange(start=1,stop=10),size=9,replace=False).reshape([3,3])
print(array2d)

[[3 6 1]
 [2 4 7]
 [5 9 8]]


**SORT BY COLUMN**


AXIS: It represents the axis along which the array is to be sorted. If the axis is not mentioned, then the sorting is done along the last available axis.

In [ ]:
np.sort(array2d,axis=0)

array([[2, 4, 1],
       [3, 6, 7],
       [5, 9, 8]])

**SORT BY ROW**

In [ ]:
np.sort(array2d,axis=1)

array([[1, 3, 6],
       [2, 4, 7],
       [5, 8, 9]])

**REVERSE IN DESCENDING**

In [ ]:
-np.sort(-array2d)

array([[6, 3, 1],
       [7, 4, 2],
       [9, 8, 5]])

**REVERSE IN ASCENDING**

In [ ]:
np.sort(array2d)

array([[1, 3, 6],
       [2, 4, 7],
       [5, 8, 9]])

**REVERSE USING STRING**

In [ ]:
#FOR SORTING
test_string = "geekforgeeks"
print("The original string : " + str(test_string))
#FOR REVERSE
res = ''.join(sorted(test_string, reverse = True))
print("String after reverse sorting : " + str(res))

The original string : geekforgeeks
String after reverse sorting : srokkggfeeee


**USING INDICES**



**numpy.argsort() function**

*This function is used to perform an indirect sort on an input array that is, it returns an array of indices of data which is used to construct the array of sorted data.*

In [ ]:
a = np.array([90, 29, 89, 12])  
print("Original array:\n",a)  
sort_ind = np.argsort(a)  
print("Printing indices of sorted data\n",sort_ind)  
sort_a = a[sort_ind]  
print("printing sorted array")  
for i in sort_ind:  
    print(a[i],end = " ") 

Original array:
 [90 29 89 12]
Printing indices of sorted data
 [3 1 2 0]
printing sorted array
12 29 89 90 

**numpy.lexsort() function**

*This function is used to sort the array using the sequence of keys indirectly. This function performs similarly to the numpy.argsort() which returns the array of indices of sorted data.*

In [ ]:
a = np.array(['a','b','c','d','e'])  
b = np.array([12, 90, 380, 12, 211])  
ind = np.lexsort((a,b))  
print("printing indices of sorted data")  
print(ind)  
print("using the indices to sort the array")  
for i in ind:  
    print(a[i],b[i])  

printing indices of sorted data
[0 3 1 4 2]
using the indices to sort the array
a 12
d 12
b 90
e 211
c 380


**numpy.nonzero() function**

*This function is used to find the location of the non-zero elements from the array.*

In [ ]:
A = np.array([12, 90, 380, 12, 211, 0, 500])  
print("printing original array",A)  
print("printing location of the non-zero elements")  
print(A.nonzero())  

printing original array [ 12  90 380  12 211   0 500]
printing location of the non-zero elements
(array([0, 1, 2, 3, 4, 6]),)


**numpy.where() function**

*This function is used to return the indices of all the elements which satisfies a particular condition.*

In [ ]:
b = np.array([12, 90, 380, 12, 211, 11, 13])  
print(np.where(b>12))  

(array([1, 2, 4, 6]),)
